export const CONTACT_LIST = "Contacts"
export const CONTACT_DETAIL = "Contact Detail"
export const CONTACT_CREATE = "Create Contact"
export const SETTINGS = "Settings"
export const LOGIN = "Login"
export const REGISTER = "Register"
export const HOME_NAVIGATOR = "Home"
